version: '3.7'
services:
  migration-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=dev
    volumes:
      - type: bind
        source: ./scripts/docker/setup-local-postgres.sql
        target: /docker-entrypoint-initdb.d/setup-local-postgres.sql
  migration-redis:
    image: "redis:6"
  migration:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - migration-db
      - migration-redis
    env_file:
      - apps/api/.env
    environment:
      - DATABASE_CONNECTION_URL=postgres://${USER}:dev@migration-db:5432/dev
      - REDIS_HOST=redis://migration-redis:6379
    entrypoint: "npx lerna run --stream --scope api migration:up"
