
services:
  dev-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dev-db
      - dev-redis
    entrypoint: 'npm run start:prod'
    env_file:
      - .env
    environment:
      - DATABASE_CONNECTION_URL=postgres://${USER}:dev@dev-db:5432/dev
      - REDIS_HOST=redis://dev-redis:6379
    ports:
      - '5333:5333'
  dev-db:
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=dev
    image: postgres:13-alpine
    volumes:
      - source: ./scripts/docker/setup-local-postgres.sql
        target: /docker-entrypoint-initdb.d/setup-local-postgres.sql
        type: bind
version: '3.7'
