version: '3.7'
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./scripts/docker/setup-local-postgres.sql
        target: /docker-entrypoint-initdb.d/setup-local-postgres.sql
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=dev
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"