name: dependapot-auto-merge

on:
  pull_request:
    paths:
      - 'apps/api/**'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: bash ./scripts/setup-ci.sh
      - run: npx lerna run --stream --scope=api lint
      - run: npx lerna run --stream --scope=api test:ci
